export { HomePage } from './HomePage'
export { DashboardPage } from './DashboardPage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { ProfilePage } from './ProfilePage'
export { TeamPage } from './TeamPage'
export { AboutPage } from './AboutPage'