export { HomePage } from "./HomePage";
export { DashboardPage } from "./DashboardPage";
export { RegisterPage } from "./RegisterPage";
export { ProfilePage } from "./ProfilePage";
export { TeamPage } from "./TeamPage";
export { AboutPage } from "./AboutPage";
export { SupportPage } from "./SupportPage";
export { HistoryPage } from "./HistoryPage";
export { AdminPage } from "./AdminPage";
export { LogoutPage } from "./LogoutPage";
export { default as VerifyEmailPage } from "./VerifyEmail";
export { default as ResetPasswordPage } from "./ResetPassword";
export { default as NotFoundPage } from "./NotFound";
export { default as ServerErrorPage } from "./ServerError";
